//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wachak
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedItem
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string pubDate { get; set; }
        public string guid { get; set; }
        public string userID { get; set; }
        public Nullable<int> savedForReading { get; set; }
        public string feedName { get; set; }
    }
}
