//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wachak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class waachakDBEntities : DbContext
    {
        public waachakDBEntities()
            : base("name=waachakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FeedItem> FeedItems { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<WaachakUser> WaachakUsers { get; set; }
        public DbSet<DefaultFeed> DefaultFeeds { get; set; }
    }
}
